### ISSUE TITLE
In classifierExecutor, token indices sequence length is longer than maximum (766 > 512)

### ISSUE THREAD

**Issue by SamTonetto** [navant/FSDL-2022-Semantic-Search-QA#37]
In main branch, test uploading a 10-Q form: [AOS_10-Q_2022-05-02.pdf](https://github.com/navant/FSDL-2022-Semantic-Search-QA/files/9780931/AOS_10-Q_2022-05-02.pdf), receive an error when pressing Fire:

> Token indices sequence length is longer than the specified maximum sequence length for this model (766 > 512). Running this sequence through the model will result in indexing errors

> ERROR  classifierExecutor/rep-0@29693 RuntimeError('The size of tensor a (766) must match the size of tensor b (512) at non-singleton dimension 1')

**Comment by francisco-perez-sorrosal** [comment]
Merged
